export default {
  application: 'my_application',
  article: 'my_article',
  attention: 'my_attention',
  bg: 'bg_my',
  chat: 'my_chat',
  collection: 'my_collection',
  fans: 'my_fans',
  next: 'my_next',
  nextWhite: 'my_next_white',
  notice: 'my_notice',
  own: 'my_own',
  setting: 'my_setting',
  suggest: 'my_suggest',
  leftBack: 'ic_input_back',
  commentCollection: 'ic_input_collection_n',
  share: 'ic_input_share',
  x: 'ic_button_del',
};
