export default {
  bg: 'bg_my',
  bgLabel: 'bg_label',

  application: 'my_application',
  article: 'my_article',
  attention: 'my_attention',
  chat: 'my_chat',
  collection: 'my_collection',
  fans: 'my_fans',
  next: 'my_next',
  nextWhite: 'my_next_white',
  notice: 'my_notice',
  own: 'my_own',
  setting: 'my_setting',
  suggest: 'my_suggest',
  leftBack: 'ic_input_back',
  commentCollection: 'ic_input_collection_n',
  share: 'ic_input_share',
  inputSearch: 'ic_input_search',
  x: 'ic_button_del',
  xCicle: 'ic_button_del_o',
  bgInput: 'bg_input',
  thumb: 'ic_like',
  thumbO: 'ic_like_o',
  search: 'ic_search',
  comment: 'ic_comments',
  approve: 'ic_approve',
  danger: 'ic_danger',
  success: 'ic_success',
  defaultHeader: 'ic_default_header',
  noticeReply: 'ic_reply',

  btnClear: 'btn_clear',
  btnDel: 'btn_del',
  btnFacial: 'btn_facial',
  btnLabel: 'btn_label',
  btnEtc: 'btn_etc',
};
