export default {
  bg: 'bg_my',
  bgLabel: 'bg_label',

  application: 'my_application',
  article: 'my_article',
  attention: 'my_attention',
  chat: 'my_chat',
  collection: 'my_collection',
  fans: 'my_fans',
  next: 'ic_small_right',
  nextWhite: 'my_next_white',
  notice: 'my_notice',
  own: 'my_own',
  setting: 'my_setting',
  suggest: 'my_suggest',
  leftBack: 'ic_input_back',
  delBack: 'header_back',
  commentCollection: 'ic_input_collection_n',
  commentCollectiono: 'ic_input_collectios',
  share: 'ic_share_n',
  detailShare: 'ic_app_details_share',
  inputSearch: 'ic_home_top_search',
  x: 'ic_button_del',
  xCicle: 'ic_button_del_o',
  bgInput: 'bg_input',
  thumb: 'ic_praise_n',
  thumbO: 'ic_like_o',
  search: 'ic_home_top_search',
  comment: 'ic_comments_n',
  approve: 'ic_user_vip_small',
  danger: 'ic_report_diolog_report',
  success: 'ic_success',
  defaultHeader: 'ic_default_header',
  noticeReply: 'ic_reply',

  btnClear: 'btn_clear',
  btnDel: 'ic_label_del',
  btnFacial: 'btn_facial',
  btnLabel: 'btn_label',
  btnEtc: 'btn_etc',

  commentLike: 'comment_btn_good',

  catComment: 'cat_comment',
  catLikeActive: 'cat_like_active',
  catLike: 'cat_like',
  catGoldActive: 'cat_gold_active',
  catGold: 'cat_gold',
  catShare: 'cat_share',
  catLocation: 'cat_location',
};
